### ISSUE TITLE
Menemukan masalah gagal logout

### ISSUE THREAD

**Issue by Ariska138** [Hyansz/portal-siswa-by-raihan#1]
Setelah logout di halaman dasboard
![image](https://github.com/Hyansz/portal-siswa-by-raihan/assets/1137972/afa1b2cd-4ed9-4774-a3ad-b60745164db2)

Pertanyaanya knp tidak ke halaman login?
```
(successData) => {
                        router.push('/login');
                      },
```

Ketika dicoba di Thunder Client
- melakukan login dan logout ternyata berhasil dan tidak ada masalah

Ketika dibuka halaman home atau login maka halaman langsung mengarah ke halaman dashboard (menemukan masalah)
masalahnya disini
```
useEffect(() => {
        const checkLoginStatus = async () => {
            const myCookieValue = getCookie("token");
            if (myCookieValue) {
                console.log("myCookieValue: ", myCookieValue);
                // router.push('/dashboard');
            }
        };

        checkLoginStatus();
    }, [router]);
```
ketika melakukan logout, data cookie tidak hilang. sehingga selalu diarahkan ke dashboard. (baik halaman login maupun di halaman logout)

- [x] pastikan hapus data di cookies ketika klik logout.
- [x] sebaiknya untuk mengarahkan ke halaman dashboard ketika ada feedback dari api (checktoken) ketika token benar-benar valid. belum tentu token yg disimpan di browser masih valid. sehingga token di broser (tanpa pengecekan di server) tidak bisa jadi dasar untuk masuk ke halaman dashboard.

**Comment by Hyansz** [comment]
Oke mas

**Comment by Hyansz** [comment]
@Ariska138 

![testing](https://github.com/Hyansz/portal-siswa-by-raihan/assets/114051543/ff54d61b-4e66-45e5-b0cc-f75ddf1b93d8)

Sudah bisa mas

**Comment by Ariska138** [comment]
sip
