### ISSUE TITLE
terdapat bug pada bagian session login

### ISSUE THREAD

**Issue by Ariska138** [Hyansz/portal-siswa-by-raihan#2]
- [x] Ketika login dengan session (tanpa centang), lalu masuk ke halaman dashboard. kemudian tutup halaman tersebut. setelah itu buka kembali halaman dashboard lewat url. seharusnya otomatis pindah ke halaman login (bukan di halaman dashboard lagi)

**Comment by Hyansz** [comment]
![bug login](https://github.com/Hyansz/portal-siswa-by-raihan/assets/114051543/9478e63b-1800-4c40-816c-a1a8b8feed3c)

@Ariska138 sudah mas

**Comment by Ariska138** [comment]
seharusnya setelah tutup tabnya. kemudian buka halaman dashboard di localhost:3000/dashboard. bukan buka di root localhost:3000.

**Comment by Ariska138** [comment]
ketika dicek ternyata sudah benar
